[package]
name = "scripst"
version = "1.1.0"
compiler = "0.13.0"
entrypoint = "src/main.typ"
authors = ["AnZreww <an112358132134@gmail.com>"]
repository = "https://github.com/An-314/typst-templates"
license = "MIT"

keywords = ["clean", "scripst", "paper", "article"]
description = "Scripst – A versatile scripting template for seamless Typst typesetting. 🚀"
categories = ["layout", "paper", "notes"]
exclude = ["/img/*", "/examples/*"]

[template]
path = "template"
entrypoint = "template/main.typ"