site_name: Scripst Documentation
docs_dir: "../../docs/zh"
site_dir: "../../scripst/zh"
site_url: https://an-314.github.io/scripst/
theme:
    name: material
    custom_dir: "../../overrides/"
    language: zh
repo_url: https://github.com/an-314/scripst
repo_name: Scripst
extra:
    alternate:
        - name: 简体中文
          link: /scripst/zh/
          lang: zh
        - name: English
          link: /scripst/
          lang: en
        - name: español
          link: /scripst/es/
          lang: es
        - name: français
          link: /scripst/fr/
          lang: fr
        - name: Deutsch
          link: /scripst/de/
          lang: de
        - name: 日本語
          link: /scripst/ja/
          lang: ja
        - name: 한국어
          link: /scripst/ko/
          lang: ko
plugins:
    - search:
          lang: zh
