site_name: Scripst Documentation
docs_dir: "../../docs/en"
site_dir: "../../scripst/"
site_url: https://an-314.github.io/scripst/
theme:
    name: material
    custom_dir: "../../overrides/"
    language: en
extra:
    alternate:
        - name: English
          link: /scripst/
          lang: en
        - name: 中文
          link: /scripst/zh/
          lang: zh
        - name: español
          link: /scripst/es/
          lang: es
        - name: français
          link: /scripst/fr/
          lang: fr
        - name: 日本語
          link: /scripst/ja/
          lang: ja
        - name: Deutsch
          link: /scripst/de/
          lang: de
plugins:
    - search:
          lang: en
